name: GitHub Actions Demo
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v3
        with:
          go-version: 1.19
      - uses: actions/checkout@v3
      - name: "fmt"
        run: test -z $(go fmt ./...)
      - name: lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: latest
          skip-go-intallation: true
          skip-pkg-cache: true
          skip-build-cache: true
          args: --timeout 2m
      - name: test
        run: go test ./...